apiVersion: apps/v1
kind: Deployment
metadata:
  name: favourite-service
  namespace: ecommerce
  labels:
    app: favourite-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: favourite-service
  template:
    metadata:
      labels:
        app: favourite-service
        version: v1
    spec:
      containers:
      - name: favourite-service
        image: ghcr.io/YOUR_USERNAME/ecommerce-favourite-service:latest
        ports:
        - containerPort: 8088
        env:
        - name: DD_AGENT_HOST
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: DD_AGENT_HOST
        - name: DD_TRACE_AGENT_PORT
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: DD_TRACE_AGENT_PORT
        - name: DD_SERVICE
          value: favourite-service
        - name: DD_ENV
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: DD_ENV
        - name: DD_VERSION
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: DD_VERSION
        - name: DD_PROFILING_ENABLED
          value: 'false'
        - name: DD_LOGS_INJECTION
          value: 'true'
        - name: DD_TRACE_ENABLED
          value: 'true'
        - name: EUREKA_URI
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config
              key: EUREKA_URI
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
          limits:
            memory: 1Gi
            cpu: 500m
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8088
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8088
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: favourite-service
  namespace: ecommerce
  labels:
    app: favourite-service
spec:
  selector:
    app: favourite-service
  ports:
  - port: 8088
    targetPort: 8088
    protocol: TCP
  type: ClusterIP
