apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ecommerce-infrastructure
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: MTIwNDIwMDM=  # base64 encoded "12042003"
  MYSQL_PASSWORD: MTIwNDIwMDM=      # base64 encoded "12042003"
---
apiVersion: v1
kind: Secret
metadata:
  name: datadog-secret
  namespace: ecommerce
type: Opaque
data:
  DD_API_KEY: eW91ci1kYXRhZG9nLWFwaS1rZXk=  # base64 encoded "your-datadog-api-key" - REPLACE THIS
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  DD_SITE: "datadoghq.com"
  DD_ENV: "development"
  DD_VERSION: "1.0.0"
  DD_AGENT_HOST: "datadog-agent.ecommerce.svc.cluster.local"
  DD_TRACE_AGENT_PORT: "8126"
  EUREKA_URI: "http://discovery-service.ecommerce.svc.cluster.local:8761/eureka"
  MYSQL_HOST: "mysql.ecommerce-infrastructure.svc.cluster.local"
  MYSQL_PORT: "3306"
  MONGODB_HOST: "mongodb.ecommerce-infrastructure.svc.cluster.local"
  MONGODB_PORT: "27017"
  KAFKA_BOOTSTRAP_SERVERS: "kafka.ecommerce-infrastructure.svc.cluster.local:9092"